/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dominio.Administrador;
import dominio.Mesa;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import uiControlador.ControladorAdministrarMesasAdministrador;
import uiInterfacesVistas.IAdministrarMesasAdministrador;
import utilidades.MesaCellRenderer;

/**
 *
 * @author Ryzen
 */
public class AdministrarMesasVista extends javax.swing.JFrame implements IAdministrarMesasAdministrador {

    private ControladorAdministrarMesasAdministrador controlador;
    private DefaultListModel<Mesa> modeloMesas;
    
    public AdministrarMesasVista(Administrador admin) {
        initComponents();
        setResizable(false);
        setTitle("Administrar Mesas");        
        this.modeloMesas = new DefaultListModel<>();
        lstMesas.setModel(modeloMesas);
        lstMesas.setCellRenderer(new MesaCellRenderer()); 
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        agregarEscuchadorCierre();    
        this.controlador = new ControladorAdministrarMesasAdministrador(this, admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMensaje = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMesas = new javax.swing.JList<>();
        btnVerMesa = new javax.swing.JButton();
        btnNuevaMesa = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblRecaudado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMensaje.setText("Total recaudado:");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("ADMINISTRAR MESAS");

        jScrollPane1.setViewportView(lstMesas);

        btnVerMesa.setText("Ver mesa");
        btnVerMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMesaActionPerformed(evt);
            }
        });

        btnNuevaMesa.setText("Nueva mesa");
        btnNuevaMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMensaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnVerMesa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevaMesa))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(379, 379, 379))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerMesa)
                    .addComponent(btnNuevaMesa))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRecaudado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMesaActionPerformed
        controlador.crearMesa();
    }//GEN-LAST:event_btnNuevaMesaActionPerformed

    private void btnVerMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMesaActionPerformed
        Mesa mesaSeleccionada = lstMesas.getSelectedValue();  // Ahora es de tipo Mesa
        if (mesaSeleccionada != null) {            
            controlador.verMesa(mesaSeleccionada);
        } else {
            lblError.setText("No has seleccionado ninguna mesa.");
        }
    }//GEN-LAST:event_btnVerMesaActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaMesa;
    private javax.swing.JButton btnVerMesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblRecaudado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Mesa> lstMesas;
    // End of variables declaration//GEN-END:variables



    @Override
    public void actualizarMesas(ArrayList<Mesa> mesas) {
        modeloMesas.removeAllElements();        
        for(Mesa m : mesas){
            modeloMesas.addElement(m);
        }  
    }

    @Override
    public void ejecutarCrearMesa() {
        CrearMesaVista cmv = new CrearMesaVista(this, false);
        cmv.setLocationRelativeTo(null);
        cmv.setVisible(true);              
    }
    
    @Override
    public void ejecutarVerMesa(Mesa mesaSeleccionada) {
        MesaDetallesDialogo mdd = new MesaDetallesDialogo(mesaSeleccionada);
        mdd.setLocationRelativeTo(null);
        mdd.setVisible(true);
    }
    
    
    @Override
    public void cerrar() {
        dispose();
    }

    @Override
    public void error(String mensaje) {
        lblError.setText(mensaje);
    }

    @Override
    public void actualizarRecaudado(float cantidad) {
        this.lblRecaudado.setText(String.valueOf(cantidad));
    }

    @Override
    public void logout() {
        this.controlador.logout();
    }
    
    public void agregarEscuchadorCierre(){
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                logout();
            }
        });
    }
}
